# Generated by Django 2.0 on 2018-09-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180922_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Post',
            new_name='author',
        ),
    ]
